apiVersion: v1
kind: Service
metadata:
  name: dkron-web
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: dkron
    component: server    
  ports:
    - protocol: TCP
      name: http
      port: 8080
